### ISSUE TITLE
MARK 催更

### ISSUE THREAD

**Issue by DragonX081** [zhan-xu/RigNet#1]
MARK 催更

**Comment by zhan-xu** [comment]
Thanks for your interests. I will release the code when ready asap.

**Comment by OneYoungMean** [comment]
同马克，希望给力(〃'▽'〃)

**Comment by zhan-xu** [comment]
Hi, due to some commercial considerations, the release of the code has to be further delayed. Sorry for that. Meanwhile, any questions about the paper and the implementation can be asked here or through my email.
