### ISSUE TITLE
＋１Cannot install the dependencies for the virtual environment

### ISSUE THREAD

**Issue by Z-Silver-Jun** [zhan-xu/RigNet#10]
Linux:I am just a user
1-The cuda version is 9.1,but I can successfully install torch1.3.0+cu100 and use it.But now torch-scatter、torch-sparse、torch-cluster ...can not be successfully installed.
ERROR: Failed building wheel for torch-scatte
ERROR: Command errored out with exit status 1: /home/xxx/anaconda3/envs/rignet/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hzg0tdiq/torch-scatter/setup.py'"'"'; __file__='"'"'/tmp/pip-install-hzg0tdiq/torch-scatter/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-mwb3ncx3/install-record.txt --single-version-externally-managed --compile --install-headers /home/xxx/anaconda3/envs/rignet/include/python3.6m/torch-scatter Check the logs for full command output.
... ...
How to solve ???? 
2-When I install the latest torch version 1.6.0,the latest torch-scatter...can be successfully installed.I try to run quick_start.py, error occurred:
RuntimeError: Detected that PyTorch and torch_scatter were compiled with different CUDA versions. PyTorch has CUDA version 10.2 and torch_scatter has CUDA version 0.0. Please reinstall the torch_scatter that matches your PyTorch install.

I wish I can find a solution:)

**Comment by Z-Silver-Jun** [comment]
Why I can successfully install torch1.3.0+cu100 and use it, but unsuccessfully install torch-scatter、torch-sparse、torch-cluster??

**Comment by zhan-xu** [comment]
Hi. I tried pytorch 1.5+ pytorch_gemetric1.5 on my machine and it works, so I think you can try install latest pytorch and pytorch_geometric (v 1.6.0). Since you system cuda is 9.1, I think it is better to use cudatool-kit in conda. Did you do exactly this?
```
conda install pytorch torchvision cudatoolkit=10.2 -c pytorch
```
After this command could you try: 

```
python -c "import torch; print(torch.__version__)"
python -c "import torch; print(torch.version.cuda)"
```
What's the outputs?
