### ISSUE TITLE
 No such file or directory: 'quick_start/17872_normalized.binvox'

### ISSUE THREAD

**Issue by jiandandian2** [zhan-xu/RigNet#12]
![image](https://user-images.githubusercontent.com/33227739/92425088-c9caa980-f1b8-11ea-9043-3f877541572a.png)

server ubuntu18.04

After i successfully install the xvfb(apt-get install xvfb) , i try to use it and i get this problem.

![image](https://user-images.githubusercontent.com/33227739/92425219-2a59e680-f1b9-11ea-8a14-9d11f21d3af3.png)

and i run the code, python quick_start.py, and i still get this problem, how to solve it?

![image](https://user-images.githubusercontent.com/33227739/92425267-4e1d2c80-f1b9-11ea-8757-c1dc6f46dc37.png)

**Comment by zhan-xu** [comment]
see #5
