### ISSUE TITLE
the dataset and pretrainmodel can't be download

### ISSUE THREAD

**Issue by youmingdeng** [zhan-xu/RigNet#13]
thanks for your reply.

**Comment by zhan-xu** [comment]
are you able to download now?

**Comment by youmingdeng** [comment]
yes，i have downloaded. thanks



    


            On 09/14/2020 22:10, Zhan Xu wrote: 
are you able to download now?

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/zhan-xu/RigNet/issues/13#issuecomment-692078388",
"url": "https://github.com/zhan-xu/RigNet/issues/13#issuecomment-692078388",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
