### ISSUE TITLE
How to drive bones like the last part of the video(https://youtu.be/J90VETgWIDg)?

### ISSUE THREAD

**Issue by youmingdeng** [zhan-xu/RigNet#14]
It's cool. what should it do? Thanks

**Comment by zhan-xu** [comment]
The animation shows one application of the predicted rigs. What we did is applying some automatic motion retargeting technique to transfer the motion from a reference animation to the predicted rigs. The correspondences here between two sets of joints are manually assigned.

**Comment by youmingdeng** [comment]
thanks

**Comment by youmingdeng** [comment]
Hi，   I am not clear how to evaluate the prec，recall，avg-dist in the skin prediction stage. Can you share the evaluation code to me？ Thanks for your help！



    


            On 09/15/2020 22:17, Zhan Xu wrote: 
The animation shows one application of the predicted rigs. What we did is applying some automatic motion retargeting technique to transfer the motion from a reference animation to the predicted rigs. The correspondences here between two sets of joints are manually assigned.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/zhan-xu/RigNet/issues/14#issuecomment-692744898",
"url": "https://github.com/zhan-xu/RigNet/issues/14#issuecomment-692744898",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by zhan-xu** [comment]
OK. As stated in our paper, the evaluation of skinning weights is performed with ground-truth skeleton, so that the error from skeleton prediction doesn't influence this part.

To evaluate skinning weights, you first run 
`python run_skinning -e --resume="checkpoints/skinnet/model_best.pth.tar" --checkpoint="checkpoints/skinnet" --train_folder='DATASET_DIR/train/' --val_folder='DATASET_DIR/val/' --test_folder='DATASET_DIR/test/' --info_folder='DATASET_DIR/rig_info_remesh/'`
This will output the skinning results in results/skinnet folder.

Then you can evaluate it with the following script

`import os
import numpy as np
import open3d as o3d
from utils.rig_parser import Info

def eval_our_model():
    info_folder = "/home/zhanxu/ModelResource_RigNetv1_preproccessed/rig_info_remesh/"
    obj_remesh_folder = "/home/zhanxu/ModelResource_RigNetv1_preproccessed/obj_remesh/"
    obj_fixed_folder = "/home/zhanxu/ModelResource_RigNetv1_preproccessed/obj/"
    output_folders = ["results/test/"]
    test_model_list = np.loadtxt('/home/zhanxu/ModelResource_RigNetv1_preproccessed/test_final.txt', dtype=np.int)

    for output_folder in output_folders:
        prec_total = []
        rec_total = []
        l1_dist_total = []
        for model_id in test_model_list:
            #model_id = 783
            #print(model_id)
            info = Info(os.path.join(info_folder, "{:d}.txt".format(model_id)))
            mesh_remesh = o3d.io.read_triangle_mesh(os.path.join(obj_remesh_folder, "{:d}.obj".format(model_id)))
            mesh_remesh_vert = np.asarray(mesh_remesh.vertices)
            mesh_fixed = o3d.io.read_triangle_mesh(os.path.join(obj_fixed_folder, "{:d}.obj".format(model_id)))
            mesh_fixed_vert = np.asarray(mesh_fixed.vertices)
            vertice_remesh_distance = np.sqrt(np.sum((mesh_remesh_vert[np.newaxis, ...] - mesh_fixed_vert[:, np.newaxis, :]) ** 2, axis=2))
            vertice_raw_id = np.argmin(vertice_remesh_distance, axis=1)
            with open(os.path.join(output_folder, '{:d}_bone_names.txt'.format(model_id)), 'r') as fin:
                lines = fin.readlines()
            bone_names = []
            for li in lines:
                bone_names.append(li.strip().split())
            skin_pred_full = np.load(os.path.join(output_folder, "{:d}_full_pred.npy".format(model_id)))

            joint_names = list(set([bone_name[0] for bone_name in bone_names]))
            skin_pred_full_new = np.zeros((len(skin_pred_full), len(joint_names)))
            for i in range(len(joint_names)):
                joint_name = joint_names[i]
                for j in range(len(bone_names)):
                    if bone_names[j][0] == joint_name:
                        skin_pred_full_new[:, i] += skin_pred_full[:, j]
            skin_pred_full = skin_pred_full_new

            skin_gt_full = np.zeros_like(skin_pred_full)
            for v in range(len(info.joint_skin)):
                skin = info.joint_skin[v]
                for w in np.arange(1, len(skin), 2):
                    col_id = joint_names.index(skin[w])
                    skin_gt_full[v, col_id] = skin[w+1]

            skin_pred_full = skin_pred_full[vertice_raw_id]
            skin_gt_full = skin_gt_full[vertice_raw_id]
            skin_pred_full = skin_pred_full[np.abs(np.sum(skin_gt_full, axis=1)-1) < 1e-2]
            skin_gt_full = skin_gt_full[np.abs(np.sum(skin_gt_full, axis=1) - 1) < 1e-2]

            precision = np.sum(np.logical_and(skin_pred_full>0, skin_gt_full>0)) / (np.sum(skin_pred_full>0) + 1e-10)
            recall = np.sum(np.logical_and(skin_pred_full>0, skin_gt_full>0)) / (np.sum(skin_gt_full>0) + 1e-10)
            mean_l1_dist = np.sum(np.abs(skin_pred_full - skin_gt_full)) / len(skin_pred_full)
            prec_total.append(precision)
            rec_total.append(recall)
            l1_dist_total.append(mean_l1_dist)
        prec_total = np.array(prec_total)
        rec_total = np.array(rec_total)
        l1_dist_total = np.array(l1_dist_total)
        print('result name: ', output_folder,
              'precision: ', np.mean(prec_total),
              'recall: ', np.mean(rec_total),
              'avg_l1_dist: ', np.mean(l1_dist_total))


if __name__ == '__main__':
    eval_our_model()`

**Comment by youmingdeng** [comment]
Hi,
&nbsp; &nbsp; &nbsp; Thansks for your reply. I have read the code, it's very clear. But I am confused about page 11 in the paper ( (c) dist measures the Euclidean distance between the position of
vertices deformed based on the reference skinning and the predicted one. To this end, given a test shape, we generate 10 different random poses,
&nbsp;and compute the average and max distance error over the mesh vertices).&nbsp;
&nbsp; &nbsp; &nbsp;The paper uses 5 evaluation indicators (Prec Rec. avg-L1 avg-dist. max-dist). There are the first 3 indicators in the code you gave, but not the last two.
&nbsp; &nbsp; &nbsp;I am not clear that each model generates the same 10 different poses ? and&nbsp;avg-dist refers to the L1 distance of the corresponding vertex of the deformed models ?
&nbsp; &nbsp; &nbsp;Can you share the evaluation code of these two indicators if it is convenient for you?&nbsp; Thanks.


Best,
Youming.&nbsp; &nbsp;



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "zhan-xu/RigNet"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月12日(星期一) 凌晨3:26
收件人:&nbsp;"zhan-xu/RigNet"<RigNet@noreply.github.com&gt;;
抄送:&nbsp;"945984093"<945984093@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [zhan-xu/RigNet] How to drive bones like the last part of the video(https://youtu.be/J90VETgWIDg)? (#14)





 
OK. As stated in our paper, the evaluation of skinning weights is performed with ground-truth skeleton, so that the error from skeleton prediction doesn't influence this part.
 
To evaluate skinning weights, you first run
 python run_skinning -e --resume="checkpoints/skinnet/model_best.pth.tar" --checkpoint="checkpoints/skinnet" --train_folder='DATASET_DIR/train/' --val_folder='DATASET_DIR/val/' --test_folder='DATASET_DIR/test/' --info_folder='DATASET_DIR/rig_info_remesh/'
 This will output the skinning results in results/skinnet folder.
 
Then you can evaluate it with the following script
 
`import os
 import numpy as np
 import open3d as o3d
 from utils.rig_parser import Info
 
def eval_our_model():
 info_folder = "/home/zhanxu/ModelResource_RigNetv1_preproccessed/rig_info_remesh/"
 obj_remesh_folder = "/home/zhanxu/ModelResource_RigNetv1_preproccessed/obj_remesh/"
 obj_fixed_folder = "/home/zhanxu/ModelResource_RigNetv1_preproccessed/obj/"
 output_folders = ["results/test/"]
 test_model_list = np.loadtxt('/home/zhanxu/ModelResource_RigNetv1_preproccessed/test_final.txt', dtype=np.int)
 for output_folder in output_folders:     prec_total = []     rec_total = []     l1_dist_total = []     for model_id in test_model_list:         #model_id = 783         #print(model_id)         info = Info(os.path.join(info_folder, "{:d}.txt".format(model_id)))         mesh_remesh = o3d.io.read_triangle_mesh(os.path.join(obj_remesh_folder, "{:d}.obj".format(model_id)))         mesh_remesh_vert = np.asarray(mesh_remesh.vertices)         mesh_fixed = o3d.io.read_triangle_mesh(os.path.join(obj_fixed_folder, "{:d}.obj".format(model_id)))         mesh_fixed_vert = np.asarray(mesh_fixed.vertices)         vertice_remesh_distance = np.sqrt(np.sum((mesh_remesh_vert[np.newaxis, ...] - mesh_fixed_vert[:, np.newaxis, :]) ** 2, axis=2))         vertice_raw_id = np.argmin(vertice_remesh_distance, axis=1)         with open(os.path.join(output_folder, '{:d}_bone_names.txt'.format(model_id)), 'r') as fin:             lines = fin.readlines()         bone_names = []         for li in lines:             bone_names.append(li.strip().split())         skin_pred_full = np.load(os.path.join(output_folder, "{:d}_full_pred.npy".format(model_id)))         joint_names = list(set([bone_name[0] for bone_name in bone_names]))         skin_pred_full_new = np.zeros((len(skin_pred_full), len(joint_names)))         for i in range(len(joint_names)):             joint_name = joint_names[i]             for j in range(len(bone_names)):                 if bone_names[j][0] == joint_name:                     skin_pred_full_new[:, i] += skin_pred_full[:, j]         skin_pred_full = skin_pred_full_new         skin_gt_full = np.zeros_like(skin_pred_full)         for v in range(len(info.joint_skin)):             skin = info.joint_skin[v]             for w in np.arange(1, len(skin), 2):                 col_id = joint_names.index(skin[w])                 skin_gt_full[v, col_id] = skin[w+1]         skin_pred_full = skin_pred_full[vertice_raw_id]         skin_gt_full = skin_gt_full[vertice_raw_id]         skin_pred_full = skin_pred_full[np.abs(np.sum(skin_gt_full, axis=1)-1) < 1e-2]         skin_gt_full = skin_gt_full[np.abs(np.sum(skin_gt_full, axis=1) - 1) < 1e-2]         precision = np.sum(np.logical_and(skin_pred_full&gt;0, skin_gt_full&gt;0)) / (np.sum(skin_pred_full&gt;0) + 1e-10)         recall = np.sum(np.logical_and(skin_pred_full&gt;0, skin_gt_full&gt;0)) / (np.sum(skin_gt_full&gt;0) + 1e-10)         mean_l1_dist = np.sum(np.abs(skin_pred_full - skin_gt_full)) / len(skin_pred_full)         prec_total.append(precision)         rec_total.append(recall)         l1_dist_total.append(mean_l1_dist)     prec_total = np.array(prec_total)     rec_total = np.array(rec_total)     l1_dist_total = np.array(l1_dist_total)     print('result name: ', output_folder,           'precision: ', np.mean(prec_total),           'recall: ', np.mean(rec_total),           'avg_l1_dist: ', np.mean(l1_dist_total))  
if name == 'main':
 eval_our_model()`

**Comment by zhan-xu** [comment]
For each model loaded into Maya, I randomly picked three joints (excluding the root joint), added a random rotation to these three joints, and saved the deformed mesh to disk. After this I compared the vertices displacement in python. So the poses are not the same. They are all randomly generated. 

Some functions you may be interested (used in mayapy):

Get all joints as a dictionary:

`def getJointDict(root):
    joint_pos = {}
    this_level = [root]
    while this_level:
        next_level = []
        for p_node in this_level:
            jpos = cmds.xform( p_node, query=True, translation=True, worldSpace=True )
            joint_pos[p_node] = {}
            joint_pos[p_node]['pos'] = jpos
            joint_pos[p_node]['ch'] = []
            ch_list = cmds.listRelatives(p_node, children=True, type='joint')
            pa_list = cmds.listRelatives(p_node, parent=True, type='joint')
            if ch_list is not None:
                joint_pos[p_node]['ch'] += ch_list
                next_level += ch_list
            if pa_list is not None:
                joint_pos[p_node]['pa'] = pa_list[0]
            else:
                joint_pos[p_node]['pa'] = 'None'
        this_level = next_level
    return joint_pos`

Add a rotation to a joint:

`cmds.rotate(angles[0], angles[1], angles[2], rot_joint, ws=True, r=True)`

**Comment by youmingdeng** [comment]
Thansks，Your paper is really graeat. If you have any new progress or papers about character animation recently, please tell me.







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhan-xu/RigNet"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月12日(星期一) 中午12:10
收件人:&nbsp;"zhan-xu/RigNet"<RigNet@noreply.github.com&gt;;
抄送:&nbsp;"945984093"<945984093@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [zhan-xu/RigNet] How to drive bones like the last part of the video(https://youtu.be/J90VETgWIDg)? (#14)





 
For each model loaded into Maya, I randomly picked three joints (excluding the root joint), added a random rotation to these three joints, and saved the deformed mesh to disk. After this I compared the vertices displacement in python. So the poses are not the same. They are all randomly generated.
 
Some functions you may be interested (used in mayapy):
 
Get all joints as a dictionary:
 
def getJointDict(root): joint_pos = {} this_level = [root] while this_level: next_level = [] for p_node in this_level: jpos = cmds.xform( p_node, query=True, translation=True, worldSpace=True ) joint_pos[p_node] = {} joint_pos[p_node]['pos'] = jpos joint_pos[p_node]['ch'] = [] ch_list = cmds.listRelatives(p_node, children=True, type='joint') pa_list = cmds.listRelatives(p_node, parent=True, type='joint') if ch_list is not None: joint_pos[p_node]['ch'] += ch_list next_level += ch_list if pa_list is not None: joint_pos[p_node]['pa'] = pa_list[0] else: joint_pos[p_node]['pa'] = 'None' this_level = next_level return joint_pos
 
Add a rotation to a joint:
 
cmds.rotate(angles[0], angles[1], angles[2], rot_joint, ws=True, r=True)

**Comment by zhan-xu** [comment]
Thank you. That means a lot to me.
