### ISSUE TITLE
quick_start Running problem

### ISSUE THREAD

**Issue by BIT-wenzi** [zhan-xu/RigNet#15]
`'.' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
Traceback (most recent call last):
  File "D:/python/pytorch/RigNet-master/quick_start.py", line 425, in <module>
    data, vox, surface_geodesic, translation_normalize, scale_normalize = create_single_data(mesh_filename)
  File "D:/python/pytorch/RigNet-master/quick_start.py", line 95, in create_single_data
    with open(mesh_filaname.replace('_remesh.obj', '_normalized.binvox'), 'rb') as fvox:
FileNotFoundError: [Errno 2] No such file or directory: 'quick_start/8210_normalized.binvox'
`
`
That big guy can give me some guidance, after a long time, it’s still the result

**Comment by zhan-xu** [comment]
This seems also the problem of failing to call binvox. Please check this https://github.com/zhan-xu/RigNet/issues/5#issuecomment-664631202. In Windows, you need to change line 94 to `os.system("binvox.exe -d 88 -pb " + mesh_filaname.replace("_remesh.obj", "_normalized.obj"))`

You are also highly recommended to test binvox.exe solely to make sure it can work under your environment.
