### ISSUE TITLE
wooooooo

### ISSUE THREAD

**Issue by BIT-wenzi** [zhan-xu/RigNet#16]
![image](https://user-images.githubusercontent.com/64357181/93429772-41ed4980-f8f4-11ea-8a5c-3246fbe072cc.png)

`Traceback (most recent call last):
  File "D:/python/pytorch/RigNet-master/gen_dataset.py", line 165, in <module>
    p.map(genDataset, [0, 1, 2, 3, 4, 5, 6, 7])
  File "D:\Anaconda3\envs\pytorch\lib\multiprocessing\pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "D:\Anaconda3\envs\pytorch\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
NameError: name 'dataset_folder' is not defined`

what is meaning？？？

The .exe file cannot be opened and cannot be installed。。。。
Also, the train and test files can be built directly under the root directory?

**Comment by zhan-xu** [comment]
Thanks for the questions. 

binvox is used as a program. You don't need to install it or open it. I call it in my code as "binvox -d 88 -pb xxxx.obj". On windows it is "binvox.exe -d 88 -pb xxxx.ob". Please refer to binvox website to see basic usage of this tool.

If you take a look at gen_dataset.py, it will create folders "train", "val" and "test" under the pre-processed dataset folder, calculate some information such as edges and skinning, and put them into corresponding sub-folder according to the split defined in "train|val|test_final.txt".

**Comment by BIT-wenzi** [comment]
However, the result of running this file is ‘name'dataset_folder' is not defined’， 
in my code 'dataset_folder = 'D:/python/pytorch/RigNet-master/ModelResource_RigNetv1_preproccessed/'
Is it because of the address?

**Comment by zhan-xu** [comment]
This is weird. Could you first use single thread (comment out `p = Pool(8)    p.map(genDataset, [0, 1, 2, 3, 4, 5, 6, 7])`, uncomment `genDataset(0)`), then print out "dataset_folder" inside function genDataset(process_id), under line `global dataset_folder`

**Comment by zhan-xu** [comment]
Also try 'dataset_folder = 'D://python//pytorch//RigNet-master//ModelResource_RigNetv1_preproccessed//'
