### ISSUE TITLE
RuntimeError: repeats must have the same size as input along dim

### ISSUE THREAD

**Issue by herunyu** [zhan-xu/RigNet#18]
Hello~ Thanks for making this great repo.
We are currently trying to use this Rignet to predict our own obj model. We have used Instant Mesh to reduce the vertices. Then input the remesh obj and use quick_start.py to predict. However, we have encountered this error：

-------------------------------------------------------------------------------------------------------------------------------
loading all networks...
     joint prediction network loaded.
     root prediction network loaded.
     connection prediction network loaded.
     skinning prediction network loaded.
creating data for model ID man
     gathering topological edges.
     calculating surface geodesic matrix.
surface geodesic calculation: 7.219671726226807 seconds
     gathering geodesic edges.
(5248, 5248)
in here

--- [binvox] mesh voxelizer, version 1.29, build #681 on 2020/01/29 09:22:12
--- written by Patrick Min, 2004-2020

Windows does not allow widths below 116, increasing dimension to 176 and performing -down as needed
  Note: setting -dmin to 1
loading model file...
MeshFileIdentifier::*create_mesh_file(quick_start/man_normalized.obj)
ObjMeshFile::load(quick_start/man_normalized.obj)
  material library:  man_normalized.mtl
  ignoring [usemtl man_normalized]
  15757 lines read
Read 10502 faces, 5248 vertices.
Mesh memory use is 16032 KB (15 MB)
  Mesh::normalize, bounding box: [-0.37032, 0, -0.084787, 1] - [0.37032, 1, 0.084787, 1]
    longest length: 1
  normalization transform:
  (1) translate [0.37032, -0, 0.084787, 1], (2) scale 1, (3) translate [0, 0, 0]
  got mesh bounding box [-0.37032, 0, -0.084787, 1] - [0.37032, 1, 0.084787, 1]

voxel model dimension: 176
GLwindow::init_lighting
Graphics card and driver information:
Vendor:   NVIDIA Corporation
Renderer: GeForce RTX 2060 SUPER/PCIe/SSE2
Version:  4.6.0 NVIDIA 445.87
Voxels::init(176, 176, 176, 0)
  Voxels::clear
Voxelizer constructor
SimpleMeshView constructor
starting voxelization...
Voxelizer::carve_voxelize
  doing x direction
  doing y direction
  doing z direction
Voxelizer::fill_voxels
  Voxels::clear
Voxelizer::parity_vote_voxelize
  doing x direction
  doing y direction
  doing z direction
Voxels::process_votes
Voxelizer::voxelize took 17.671 seconds
Voxels::downsample
Voxels::print_filled_area
Voxels::compute_bounding_box
  area filled: 65 x 15 x 88
  integer bounding box: [0,0,0] - [64,14,87]
Voxels::print_count
  counted 9790 set voxels out of 681472

writing voxel file...
VoxelFile::write_file(quick_start/man_normalized.binvox)
Wrote 9790 set voxels out of 681472, in 7908 bytes
done

predicting joints
predicting connectivity
Traceback (most recent call last):
  File "quick_start.py", line 440, in <module>
    mesh_filename=mesh_filename.replace("_remesh.obj", "_normalized.obj"))
  File "quick_start.py", line 187, in predict_skeleton
    connect_prob, _ = bone_pred_net(input_data, permute_joints=False)
  File "C:\Users\h\Miniconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\Workspace\RigNet\models\PairCls_GCN.py", line 112, in forward
    joint_feature = torch.repeat_interleave(joint_feature, torch.bincount(data.pairs_batch), dim=0)
RuntimeError: repeats must have the same size as input along dim

-----------------------------------------------------------------------------------------------------------------------------------------

 Could you please take a look to see what possibly goes wrong? Thank you

**Comment by zhan-xu** [comment]
Hi. Could you please send me the model you are using? Or do you also have this problem when using my provided models?

**Comment by herunyu** [comment]
> Hi. Could you please send me the model you are using? Or do you also have this problem when using my provided models?

No problem with your original bird model in quick_start.py. I've just sent you the model. The problem for now only pops up with our model.  Please take a look. Thanks~

**Comment by tamakoji** [comment]
Hello, how this was done to solve? I also have same issue (with only the model I have)

**Comment by zhan-xu** [comment]
@tamakoji Hi, I tried with your model and didn't reproduce the same problem. 

![wolf_joints](https://user-images.githubusercontent.com/3896000/98705236-7f49e280-234b-11eb-952e-82159a94d9ee.png)

Did you use the latest version of code? As I remember, the problem from @herunyu came from the old version they used at first.

**Comment by tamakoji** [comment]
@zhan-xu thank you for your prompt feedback. I use commit 9cd489f22097e7b5152d39ca0e72d1e5a83df6fa and the only difference is that parameter is set as 
```model_id, bandwidth, threshold = "wolf", 0.429, 1e-5```
in `quick_start.py`.
I see function `predict_joints` returning the `input_data.pairs_batch` with empty tensor(tensor([], dtype=torch.int64), making bincount also empty.

**Comment by tamakoji** [comment]
maybe the line [here](https://github.com/zhan-xu/RigNet/blob/9cd489f22097e7b5152d39ca0e72d1e5a83df6fa/quick_start.py#L416) should be `0.0429` instead of `0.429`?
I just set the value to `0.0429` and it passes with non empty tensor (still running now)

**Comment by zhan-xu** [comment]
Good catch. I will change here. btw, you can set `model_id, bandwidth, threshold = "wolf", 0.429, 1e-5` to use the default bandwidth.

**Comment by tamakoji** [comment]
Thank you. Could you paste the parameter to obtain the one you posted above? I still can't make parameters nice to be like the of yours.
![image](https://user-images.githubusercontent.com/7410464/98711000-44d74a00-2339-11eb-8f53-ef26c7c0ec22.png)

**Comment by tamakoji** [comment]
oh maybe I had to delete some cache files (normalized or simplified obj/mtl) to perform again. now seems pretty good!
![image](https://user-images.githubusercontent.com/7410464/98712098-b49a0480-233a-11eb-8fc6-ff3e2e6d454e.png)
