### ISSUE TITLE
any Plan to support glb/gltf models? 

### ISSUE THREAD

**Issue by arpu** [zhan-xu/RigNet#19]
Hey,

do you plan include the open glb/gltf format  for the models? 

https://www.khronos.org/gltf/

**Comment by zhan-xu** [comment]
Hi. The training process doesn't rely on a specific format. No matter what format the original models are (in fbx or gltf), you have to parse them into the files such as *.obj, *_rig_info.txt, and also pre-calculate "pretrain_attention", "volumetric_geodesic" and the voxelizations. See the "Data" section in README for the data directly used for training.

For me, I downloaded all models as Collada files at the very first, and use pycollada and Maya to parse them. This part of code may not be made public.

However, I provided an example here (https://github.com/zhan-xu/RigNet/issues/8#issuecomment-670556536) to parse fbx into obj and rig_info.txt via Mayapy (currently supports single geometry group and skinning). If you can import gltf into Maya, you can try parse the imported model similarly as this script.

**Comment by arpu** [comment]
thx a lot for the information, will try!

**Comment by arpu** [comment]
i think this can be closed
