### ISSUE TITLE
在线等~

### ISSUE THREAD

**Issue by potazhou** [zhan-xu/RigNet#2]

**Comment by zhan-xu** [comment]
Hi, due to some commercial considerations, the release of the code has to be further delayed. Sorry for that. Meanwhile, any questions about the paper and the implementation can be asked here or through my email.

**Comment by saliAlavi** [comment]
Shame. How late?

**Comment by HappyOcean** [comment]
reasonably understandable. I guess this will be potentially going to have huge impact.
Keep up! waiting for it.

**Comment by potazhou** [comment]
> Hi, due to some commercial considerations, the release of the code has to be further delayed. Sorry for that. Meanwhile, any questions about the paper and the implementation can be asked here or through my email.

I am so sad to hear that but thanks for your study！
