### ISSUE TITLE
./binvox: Permission denied

### ISSUE THREAD

**Issue by jiandandian2** [zhan-xu/RigNet#21]
![image](https://user-images.githubusercontent.com/33227739/95650827-c0669100-0b18-11eb-91b6-34193a0a665b.png)
mistake using it in pycharm

**Comment by zhan-xu** [comment]
I also use pycharm and it works. Can you use binvox from terminal?

**Comment by zhan-xu** [comment]
https://esmithy.net/2015/05/05/rundebug-as-root-in-pycharm/
