### ISSUE TITLE
Maya alternative to producing rigs

### ISSUE THREAD

**Issue by tdeeb** [zhan-xu/RigNet#23]
Hello, thanks so much for building RigNet; it's very impressive! I was wondering if there is an alternative to Maya for combining the resulting .obj and .txt files into an .fbx. Is it possible to provide a script for Blender?

**Comment by zhan-xu** [comment]
Hi, I am sorry I am not very familiar with Blender scripting. I will have to learn that, so will leave this for future work. 

One can parse the resulting .txt file according to the description in README->DATA->rig_info, and with the APIs provided by Blender for rigging, one might be able to visualize things in Blender as well.

**Comment by pKrime** [comment]
Hello,

@tdeeb 
I have implemented RigNet as a blender addon. It makes possible to generate rigs directly in blender, or it can load already made rigs parsing their .txt files

please check it here
https://github.com/pKrime/brignet

video here
https://youtu.be/ueLlS3IoeGY

@zhan-xu 
Thanks a lot for making this all available: I have tried my best not to overlook any credits or restrictions, but please let me know if any changes are due

Cheers!

**Comment by zhan-xu** [comment]
@pKrime Thanks for your excellent work! I assume this is something that many people are interested in. I will put the link to my REAME as well.

**Comment by zhan-xu** [comment]
Hi @pKrime may I have your email? Would like to discuss with you. 
You may shoot me an email at zhaxu@adobe.com, or zhanxu@cs.umass.edu.
