### ISSUE TITLE
cmds.file(obj_name, o=True)  RuntimeError

### ISSUE THREAD

**Issue by wingdi** [zhan-xu/RigNet#26]
when i run maya_save_fbx.py using mayapy ,  i got this Error . 

pymel.internal.startup : WARNING : Maya startup file C:/Users/Administrator/Documents/maya\2019\prefs\userNamedCommands.mel does not exist
pymel.internal.startup : WARNING : Maya startup file C:/Users/Administrator/Documents/maya\2019\prefs\pluginPrefs.mel does not exist
smith
Traceback (most recent call last):
  File "D:\OpenProject\RigNet-master\RigNet-master\maya_save_fbx.py", line 94, in <module>
    cmds.file(obj_name, o=True)
RuntimeError

env : autodesk maya 2019、 win10、numpy you provided

I have  run quick_start.py successfully.

**Comment by zhan-xu** [comment]
Hello. Did you run maya_save_fbx.py inside Maya script editor?

**Comment by wingdi** [comment]
thanks for quick  reply.
I just tried ,  when run it inside Maya script editor or  used Pycharm's terminal .  I got the same above error. 

and when i installed numpy you provided , i got this Error:
```
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

tifffile 2020.10.1 requires numpy>=1.15.1, but you'll have numpy 1.13.1 which is incompatible.
scipy 1.5.4 requires numpy>=1.14.5, but you'll have numpy 1.13.1 which is incompatible.
scikit-image 0.17.2 requires numpy>=1.15.1, but you'll have numpy 1.13.1 which is incompatible.
pywavelets 1.1.1 requires numpy>=1.13.3, but you'll have numpy 1.13.1 which is incompatible.
opencv-python 4.4.0.46 requires numpy>=1.14.5, but you'll have numpy 1.13.1 which is incompatible.
matplotlib 3.3.2 requires numpy>=1.15, but you'll have numpy 1.13.1 which is incompatible.

```
maybe this in connection with that Error?

**Comment by zhan-xu** [comment]
how did you install numpy? I used maya 2019 and 2020 on windows 64bit. The way to configure numpy for mayapy is downloading pre-compiled libs and and putting them to the corresponding path. I followed this post https://forums.autodesk.com/t5/maya-programming/guide-how-to-install-numpy-scipy-in-maya-windows-64-bit/td-p/5796722

Seems you used pip to install?

As a quick sanity check, you can start Maya, and click the "MEL" button to switch it into "PYTHON". You can then run single line of code here. Try to run "import numpy as np" or "import maya.cmds as cmds". Any possible error will be shown in the script editor. Check if your mayapy is good and numpy is ready to use.

**Comment by wingdi** [comment]
yes,  after run  import numpy as np ;   import maya.cmds as cmds ;   import maya.OpenMaya as om .  the maya python script editor didn't show any Error . 
![批注 2020-11-18 004818](https://user-images.githubusercontent.com/25787391/99420299-07298100-2938-11eb-8ada-e6212ff0df1f.png)

I run maya_save_fbx.py using mayapy.exe   use the  command :  execfile('D:\OpenProject\RigNet-master\RigNet-master\maya_save_fbx.py') .  is it right ?  

mine env:  win10、win64、 6G GPU

**Comment by zhan-xu** [comment]
could you try to simply copy maya_save_fbx.py into the python editor and run (by clicking the green arrow on the top)?

**Comment by wingdi** [comment]
yes , through run maya_save_fbx.py's code using maya python editor, i find the error :  i need change obj_name's value to "obj_name = 'D:\\OpenProject\\RigNet-master\\RigNet-master\\quick_start\\{:s}_ori.obj'.format(model_id)' " ，it's a very simple Error ,  thanks very much  !

now I can get smith.fbx ：
![批注 2020-11-18 092929](https://user-images.githubusercontent.com/25787391/99471100-e89ba800-2980-11eb-9044-dc2e69974c92.png)

with some warning:
错误: file: C:/Allegorithmic/SubstanceMaya/2019/scripts/userSetup.mel line 54: UI 命令无法在批处理模式下运行。
smith
文件读取所用时间为  0.023 秒。
警告: 无法将某些权重设置为指定的值。权重总计可能已超过 1.0。
警告: 无法将某些权重设置为指定的值。权重总计可能已超过 1.0。
警告: 无法将某些权重设置为指定的值。权重总计可能已超过 1.0。
警告: 无法将某些权重设置为指定的值。权重总计可能已超过 1.0。
警告: 无法将某些权重设置为指定的值。权重总计可能已超过 1.0。
警告: 无法将某些权重设置为指定的值。权重总计可能已超过 1.0。

**Comment by zhan-xu** [comment]
yeah I also got these warnings. I think it is because of float precision, and Maya will automatically crop them to make the summation to 1.0.
