### ISSUE TITLE
pytorch1.7 instead pytorch1.6.0 in current dependency setup

### ISSUE THREAD

**Issue by fatboYY** [zhan-xu/RigNet#29]
Hey,

currently after running the dependency setup pytorch is being resolved to 1.7 instead of 1.6.0.

**Comment by zhan-xu** [comment]
Hi, thanks for pointing that out. Have you tried that everything works well after changing `conda install pytorch`  to `conda install pytorch-1.6.0`?

**Comment by zhan-xu** [comment]
Take a look at this one: https://github.com/zhan-xu/RigNet/issues/24#issuecomment-722203461
Maybe we can keep this since it explicitly specify versions for all libraries.

**Comment by fatboYY** [comment]
Hey,
I did a fresh anaconda setup with #30 on Windows today and it worked well.
I would like to avoid the change proposed in #24 since it's locked to Linux.

**Comment by zhan-xu** [comment]
Can we change it to 
`# CUDA 10.1
conda install pytorch==1.6.0 torchvision==0.7.0 cudatoolkit=10.1 -c pytorch
`
according to https://pytorch.org/get-started/previous-versions/?

**Comment by fatboYY** [comment]
Yeah we could do that. This is what my torch related packages look like:

```
conda list torch
WARNING: The conda.compat module is deprecated and will be removed in a future release.
# packages in environment at C:\Users\MK\Anaconda3\envs\rignet:
#
# Name                    Version                   Build  Channel
pytorch                   1.6.0           py3.7_cuda101_cudnn7_0    pytorch
torch-cluster             1.5.8                    pypi_0    pypi
torch-geometric           1.6.1                    pypi_0    pypi
torch-scatter             2.0.5                    pypi_0    pypi
torch-sparse              0.6.8                    pypi_0    pypi
torch-spline-conv         1.2.0                    pypi_0    pypi
torchvision               0.7.0                py37_cu101    pytorch
```

If I have time to invest a bit more into the setup I'd like to set up a `environment.yml`

**Comment by zhan-xu** [comment]
great! Merged.

**Comment by ArashHosseini** [comment]
@zhan-xu just for you to know, i tested the code with cuda 11 and everything went fine, check [fork] pls(https://github.com/ArashHosseini/RigNet)

**Comment by zhan-xu** [comment]
Thanks @ArashHosseini . I will mention your repo if someone asks.
