### ISSUE TITLE
The process killed in quick_start.py

### ISSUE THREAD

**Issue by Xianjin111** [zhan-xu/RigNet#32]
Hi,

Thanks for your perfect work. I have problems in quick_start.py. When I run the quick_strat.py in Linux, it will be always killed like this:

loading all networks...
     joint prediction network loaded.
     root prediction network loaded.
     connection prediction network loaded.
     skinning prediction network loaded.
creating data for model ID 1347
     gathering topological edges.
     calculating surface geodesic matrix.
Killed

Has anyone encountered the same problem and how to solve it.
Thx

**Comment by zhan-xu** [comment]
This seems due to RAM memory limitation. If your memory is not enough (below 16G), you may need to downsample more progressively during volumetric geodesic distance calculation. See line 229-236 in quick_start.py.

**Comment by yimengliu0216** [comment]
Hi! I have encountered the same issue. Can you please specify how to adjust the downsampling rates? Thanks!
