### ISSUE TITLE
Problem when run run_joint_pretrain.py!!

### ISSUE THREAD

**Issue by xufengfan96** [zhan-xu/RigNet#33]
Hello author,I have read your paper and I really think it's a great work.I download the pre-processed data and run gen_dataset.py. When I run run_joint_pretrain.py,I meet a mistake "RuntimeError: cannot perform reduction function min on tensor with no elements because the operation does not have an identity".Here is the all message:
Namespace(aggr='max', arch='jointnet', checkpoint='checkpoints/pretrain_jointnet', epochs=100, evaluate=False, gamma=0.2, input_normal=False, logdir='logs/pretrain_jointnet', lr=0.0005, resume='', schedule=[50], start_epoch=0, test_batch=6, test_folder='/home/lab505/rignet/RigNet-master/data/ModelResource_RigNetv1_preproccessed/test/', train_batch=6, train_folder='/home/lab505/rignet/RigNet-master/data/ModelResource_RigNetv1_preproccessed/train/', val_folder='/home/lab505/rignet/RigNet-master/data/ModelResource_RigNetv1_preproccessed/val/', weight_decay=0.0001)
    Total params: 3.83M

Epoch: 1 | LR: 0.00050000
Traceback (most recent call last):
  File "run_joint_pretrain.py", line 212, in <module>
    main(parser.parse_args())
  File "run_joint_pretrain.py", line 94, in main
    train_loss = train(train_loader, model, optimizer, args)
  File "run_joint_pretrain.py", line 138, in train
    loss += chamfer_distance_with_average(y_pred_i.unsqueeze(0), joint_gt.unsqueeze(0))
  File "/home/lab505/rignet/RigNet-master/models/supplemental_layers/pytorch_chamfer_dist.py", line 22, in chamfer_distance_with_average
    dist1 = torch.min(dist_norm, dim=1)[0]
RuntimeError: cannot perform reduction function min on tensor with no elements because the operation does not have an identity

**Comment by xufengfan96** [comment]
Can you know what happened? I think I deal with the data in a right way.

**Comment by xufengfan96** [comment]
In train ,test, val floders I can see the processed.Only the checkpoint has no file.

**Comment by zhan-xu** [comment]
Can you check if your train_loader successfully load the processed data? Is there a train_skeleton_data.pt in train/processed?

**Comment by xufengfan96** [comment]
> Can you check if your train_loader successfully load the processed data? Is there a train_skeleton_data.pt in train/processed?
Yes, there is a train_skeleton_data.py(1.4GB) in train/processed.And I print train_loader.dataset. It shows GraphDataset(2163).

**Comment by xufengfan96** [comment]
> Can you check if your train_loader successfully load the processed data? Is there a train_skeleton_data.pt in train/processed?

Yes, there is a train_skeleton_data.py(1.4GB) in train/processed.And I print train_loader.dataset. It shows GraphDataset(2163).
My torch version is 1.6.0+cu101 and torch-geometric version is 1.6.2

**Comment by zhan-xu** [comment]
ok, so the data loader is good. It seems in line 138, either y_pred_i or joint_gt is empty. Could you debug to see which one is empty and which step does it come from?

**Comment by xufengfan96** [comment]
I find the problem in function train.So I add this part in line 126:
q=0
    for data in train_loader:
        q+=1
        print('q:{},data:{}'.format(q,data))
And I get this result:
q:360,data:Batch(batch=[12015], geo_edge_index=[2, 120151], joints=[160, 3], joints_batch=[160], mask=[12015], name=[6], pair_attr=[2285, 3], pairs=[2285, 2], pos=[12015, 3], tpl_edge_index=[2, 82679], x=[12015, 3])
q:361,data:Batch(batch=[6073], geo_edge_index=[2, 62171], joints=[59, 3], joints_batch=[59], mask=[6073], name=[3], pair_attr=[631, 3], pairs=[631, 2], pos=[6073, 3], tpl_edge_index=[2, 41469], x=[6073, 3])
......
RuntimeError: cannot perform reduction function min on tensor with no elements because the operation does not have an identity
It looks like some datas is wrong.And I run gen_dataset again it doesn't work.

**Comment by zhan-xu** [comment]
However from the print-out, even for q=361, all attributes have identity. Are you using train_batch=1? Does it always crash at this particular data (the "name" attribute can be seen as IDs for all data)? 

Also, could you step into line 132 of run_joint_pretrain.py, which should be line 31-52 in models/GCN.py, and see which step causes the problem?

**Comment by xufengfan96** [comment]
> However from the print-out, even for q=361, all attributes have identity. Are you training with train_batch=1? Does it always crash at this particular data (the "name" attribute can be seen as IDs for all data)?
> 
> Also, could you step into line 132 of run_joint_pretrain.py, which should be line 31-52 in models/GCN.py, and see which step causes the problem?

I think I find the problem.My train_batch is 6. The number of train data is 2163. And 361*6=2166,so the last part only have 3 data.Maybe the GCN's input_normal is 6 so I meet the problem.When I training with train_batch=3 it can work know.Thanks in advance for your patience.

**Comment by zhan-xu** [comment]
I used 1080Ti or TitanX, so basically 10-11G GPU memory for training.

**Comment by xufengfan96** [comment]
> I used 1080Ti or TitanX, so basically 10-11G GPU memory for training.

Thank you for your help!Now it can work!
