### ISSUE TITLE
Evaluation setting about parameters

### ISSUE THREAD

**Issue by countywest** [zhan-xu/RigNet#34]
Hello~! I have a question about your paper.
In`quick_start.py`,  we can control the level of details of rig with different bandwidth.
I also empirically found that slight difference in the value of threshold can change the rigging results quite a lot.
So my question is, how can we set the bandwidth and threshold value when we want to evaluate quantitatively?
I think the bandwidth can be the learnt value from the training set, but I have a doubt about setting the values of threshold to all 0.
Is there no problem about that? and, How did you set the threshold value?

**Comment by zhan-xu** [comment]
The default setting is to set bandwidth=None and threshold=1e-5, as said in the comments line 426 in quick_start.py
