### ISSUE TITLE
About comparison with Pinocchio

### ISSUE THREAD

**Issue by whitealex95** [zhan-xu/RigNet#35]
Hi, in your paper, you did comparison with the work from Pinocchio.
However, some of the meshes in your dataset won't work with the code they provided(https://github.com/pmolodo/Pinocchio)
(I see that some of the meshes are not the boundary of the connected volume, which is a restriction the authors of the Pinocchio mentioned..)
can you share with us how you managed work

**Comment by zhan-xu** [comment]
You will need to convert polygon soup into watertight manifold first. Try https://github.com/hjwdzh/Manifold, or first sample on the surface and apply Poisson reconstruction.
