### ISSUE TITLE
No such file or directory: 'quick_start/17872_normalized.binvox'

### ISSUE THREAD

**Issue by PJ-Hunter** [zhan-xu/RigNet#39]
When i run quick_start.py, i meet this problem. Could you please help me solve this problem?
![image](https://user-images.githubusercontent.com/30943144/112447864-c1b90c80-8d8c-11eb-94dd-1e0b12300189.png)

**Comment by zhan-xu** [comment]
Seems binvox is not called properly. It says permission denied. Could you first make sure you can call binvox on the machine?
https://www.patrickmin.com/binvox/

**Comment by UESTCPG** [comment]
> Seems binvox is not called properly. It says permission denied. Could you first make sure you can call binvox on the machine?
> https://www.patrickmin.com/binvox/

i install xvfb (apt-get install xvfb), but the above error still occurs (sh: 1: ./binvox: Permission denied).

**Comment by UESTCPG** [comment]
> Seems binvox is not called properly. It says permission denied. Could you first make sure you can call binvox on the machine?
> https://www.patrickmin.com/binvox/

i have solved the problem (sh: 1: ./binvox: Permission denied) through input "chmod +x" and can output the skeleton on your model. However, I set the default parameter (bandwidth=None, threshold=1e-5) and the number of vertex is between 1k and 5k. When i try to produce the skeleton with my own model, the following error occurs. It seems that the vertex_normals cannot be computed. May i send my model to you by email and you test the model? Thanks!
![image](https://user-images.githubusercontent.com/30943144/112746356-c2e27780-8fe0-11eb-8ec1-60e3596b6c96.png)
![image](https://user-images.githubusercontent.com/30943144/112746367-d55cb100-8fe0-11eb-9beb-0d8d9b8863bf.png)

**Comment by zhan-xu** [comment]
Hi, thanks for pointing this out. There is a mistake that I have corrected. Please pull the latest version and try again. Thanks!

**Comment by UESTCPG** [comment]
> Hi, thanks for pointing this out. There is a mistake that I have corrected. Please pull the latest version and try again. Thanks!

Thanks for your correcting. i download the latest version and run my model, but it seems that the result looks not as good as your example. i have set the default parameters (bandwidth=None, threshold=1e-5). Could you please tell me the reason? Thanks!
![image](https://user-images.githubusercontent.com/30943144/112779952-659b0480-907a-11eb-9b34-9ff0c605da32.png)

**Comment by zhan-xu** [comment]
We have that constrain that the input is symmetric and normalized. The input mesh is supposed to be in T-pose.
