### ISSUE TITLE
Issue running quick_start.py

### ISSUE THREAD

**Issue by imsherlock** [zhan-xu/RigNet#4]
I get the following error when trying to run quick_start.py

```
root@a2349b494f3e:/workspace/RigNet# python3 quick_start.py
Traceback (most recent call last):
  File "quick_start.py", line 31, in <module>
    from run_skinning import post_filter
  File "/workspace/RigNet/run_skinning.py", line 26, in <module>
    from datasets.skin_dataset import SkinDataset
ModuleNotFoundError: No module named 'datasets'
```

I've installed all the Python modules listed in the README. Is there another that needs to be installed? Or a missing directory in the repository?

**Comment by zhan-xu** [comment]
Thanks for the feedback. I just uploaded the dataset module. It should be a folder in the root directory.

**Comment by imsherlock** [comment]
That seems to have gotten me through. Thanks @zhan-xu ! I'll go ahead and close the issue.
