### ISSUE TITLE
quick_start/17872_normalized.obj: Permission denied

### ISSUE THREAD

**Issue by A6248384** [zhan-xu/RigNet#40]
Thank for this project!
I got an error when I run python quick_start.py

loading all networks...
     joint prediction network loaded.
     root prediction network loaded.
     connection prediction network loaded.
     skinning prediction network loaded.
creating data for model ID 17872
     gathering topological edges.
     calculating surface geodesic matrix.
surface geodesic calculation: 9.081551790237427 seconds
     gathering geodesic edges.
sh: 1: quick_start/17872_normalized.obj: Permission denied
Traceback (most recent call last):
  File "quick_start.py", line 440, in <module>
    data, vox, surface_geodesic, translation_normalize, scale_normalize = create_single_data(mesh_filename)
  File "quick_start.py", line 103, in create_single_data
    with open(mesh_filaname.replace('_remesh.obj', '_normalized.binvox'), 'rb') as fvox:
FileNotFoundError: [Errno 2] No such file or directory: 'quick_start/17872_normalized.binvox'

Is there any solution?

**Comment by zhan-xu** [comment]
are you able to run binvox byitself?

**Comment by A6248384** [comment]
I run ./binvox and this is the result.

--- [binvox] mesh voxelizer, version 1.26, build #644 on 2017/10/22 15:19:22
--- written by Patrick Min, 2004-2017

Error: missing model filename

Usage: binvox [-d <voxel dimension>] [-t <voxel file type>] [-c] [-v] <model filespec>
  -license: show software license
  -d: specify voxel grid size (default 256, max 1024)(no max when using -e)
  -t: specify voxel file type (default binvox, also supported: hips, mira, vtk, raw, schematic, msh)
  -c: z-buffer based carving method only
  -dc: dilated carving, stop carving 1 voxel before intersection
  -v: z-buffer based parity voting method only (default is both -c and -v)
  -e: exact voxelization (any voxel with part of a triangle gets set)(does not use graphics card)
Additional parameters:
  -bb <minx> <miny> <minz> <maxx> <maxy> <maxz>: force a different input model bounding box
  -ri: remove internal voxels
  -cb: center model inside unit cube
  -rotx: rotate object 90 degrees ccw around x-axis before voxelizing
  -rotz: rotate object 90 degrees cw around z-axis before voxelizing
    both -rotx and -rotz can be used multiple times
  -aw: _also_ render the model in wireframe (helps with thin parts)
  -fit: only write the voxels in the voxel bounding box
  -bi <id>: when converting to schematic, use block ID <id>
  -mb: when converting using -e from .obj to schematic, parse block ID from material spec 'usemtl blockid_<id>' (ids 1-255 only)
  -pb: use offscreen pbuffer instead of onscreen window
  -down: downsample voxels by a factor of 2 in each dimension (can be used multiple times)
  -dmin <nr>: when downsampling, destination voxel is on if >= <nr> source voxels are (default 4)
Supported 3D model file formats:
  VRML V2.0: almost fully supported
  UG, OBJ, OFF, DXF, XGL, POV, BREP, PLY, JOT: only polygons supported
Example:
binvox -c -d 200 -t mira plane.wrl

**Comment by zhan-xu** [comment]
Yeah you need to pass a model to it and test. Check binvox webpage for the usage.

**Comment by A6248384** [comment]
I try this command.
!./binvox -d 88 -pb quick_start/17872_remesh.obj

--- [binvox] mesh voxelizer, version 1.26, build #644 on 2017/10/22 15:19:22
--- written by Patrick Min, 2004-2017

  will use offscreen pbuffer instead of onscreen window
loading model file...
MeshFileIdentifier::*create_mesh_file(quick_start/17872_remesh.obj)
ObjMeshFile::load(quick_start/17872_remesh.obj)
4102 quick_start/17872_remesh.obj
  4103 lines read
Read 2020 faces, 1040 vertices.
Mesh memory use is 2096 KB (2 MB)
  Mesh::normalize, bounding box: [-0.5, 0, -0.32287, 1] - [0.5, 0.436996, 0.32287, 1]
    longest length: 1
  normalization transform:
  (1) translate [0.5, -0, 0.32287, 1], (2) scale 1, (3) translate [0, 0, 0]
freeglut (./binvox): failed to open display ''

**Comment by zhan-xu** [comment]
Did you get quick_start/17872_normalized.obj?

**Comment by A6248384** [comment]
quick_start/17872_normalized.obj and quick_start/17872_normalized.mtl
I run python quick_start.py again and I got this.

loading all networks...
     joint prediction network loaded.
     root prediction network loaded.
     connection prediction network loaded.
     skinning prediction network loaded.
creating data for model ID 17872
     gathering topological edges.
     calculating surface geodesic matrix.
surface geodesic calculation: 9.594509601593018 seconds
     gathering geodesic edges.

--- [binvox] mesh voxelizer, version 1.26, build #644 on 2017/10/22 15:19:22
--- written by Patrick Min, 2004-2017

  will use offscreen pbuffer instead of onscreen window
loading model file...
MeshFileIdentifier::*create_mesh_file(quick_start/17872_normalized.obj)
ObjMeshFile::load(quick_start/17872_normalized.obj)
3066 quick_start/17872_normalized.obj
  material library:  17872_normalized.mtl
  ignoring [usemtl 17872_normalized]
  3067 lines read
Read 2020 faces, 1040 vertices.
Mesh memory use is 1836 KB (1 MB)
  Mesh::normalize, bounding box: [-0.5, 0, -0.32287, 1] - [0.5, 0.436996, 0.32287, 1]
    longest length: 1
  normalization transform:
  (1) translate [0.5, -0, 0.32287, 1], (2) scale 1, (3) translate [0, 0, 0]
freeglut (./binvox): failed to open display ''
Traceback (most recent call last):
  File "quick_start.py", line 440, in <module>
    data, vox, surface_geodesic, translation_normalize, scale_normalize = create_single_data(mesh_filename)
  File "quick_start.py", line 103, in create_single_data
    with open(mesh_filaname.replace('_remesh.obj', '_normalized.binvox'), 'rb') as fvox:
FileNotFoundError: [Errno 2] No such file or directory: 'quick_start/17872_normalized.binvox'

**Comment by zhan-xu** [comment]
when you try ./binvox -d 88 -pb quick_start/17872_remesh.obj, did you get quick_start/17872_remesh.binvox?

**Comment by A6248384** [comment]
when I try  ./binvox -d 88 -pb quick_start/17872_remesh.obj. I didn't get quick_start/17872_remesh.binvox 
I just got following error.

--- [binvox] mesh voxelizer, version 1.26, build #644 on 2017/10/22 15:19:22
--- written by Patrick Min, 2004-2017

will use offscreen pbuffer instead of onscreen window
loading model file...
MeshFileIdentifier::*create_mesh_file(quick_start/17872_remesh.obj)
ObjMeshFile::load(quick_start/17872_remesh.obj)
4102 quick_start/17872_remesh.obj
4103 lines read
Read 2020 faces, 1040 vertices.
Mesh memory use is 2096 KB (2 MB)
Mesh::normalize, bounding box: [-0.5, 0, -0.32287, 1] - [0.5, 0.436996, 0.32287, 1]
longest length: 1
normalization transform:
(1) translate [0.5, -0, 0.32287, 1], (2) scale 1, (3) translate [0, 0, 0]
freeglut (./binvox): failed to open display ''

**Comment by zhan-xu** [comment]
It is same issue as in #5 
please check that thread. One quick try it to remove -pb

**Comment by zhan-xu** [comment]
Seems it is not easy to solve. I will update the code to get rid of binvox when I have time asap.

**Comment by A6248384** [comment]
Thank's for your reply.
I think it's my setting problem. I use this project on virtual machine and can't display anything.

**Comment by yisuanwang** [comment]
> It is same issue as in #5 please check that thread. One quick try it to remove -pb

Error: cannot get XVisualInfo from fbconfig
Error: could not create pbuffer
