### ISSUE TITLE
Use CUDA 11

### ISSUE THREAD

**Issue by fire** [zhan-xu/RigNet#48]
I have a lot of trouble using the 3000 series gpu because CUDA 11 is required.

Upgrading to CUDA 11 on this repo failed for me.

**Comment by devilismyfriend** [comment]
Did you ever figure it out?

**Comment by fire** [comment]
There was no response and I did not.

**Comment by devilismyfriend** [comment]
Someone actually made a fork of it for cuda 11
https://github.com/ArashHosseini/RigNet_Cuda11

It worked for me (although outside of the examples given I can't get good results from this network)

**Comment by zhan-xu** [comment]
Hi, I have updated the readme. I tested with cuda11 and seems it works ok. Let me know if you still have problem!
