### ISSUE TITLE
Simplified Blender addon

### ISSUE THREAD

**Issue by L-Medici** [zhan-xu/RigNet#52]
Hello, me and my colleagues made a blender addon as a project for one of our exam at university. It's a really straight forward and fast setup that utilize your Rignet and checkpoints's models as choosable character to rig. Hope you'll like it and thank you for all your hard work, you do really cool stuff <3

https://github.com/L-Medici/Rignet_blender_addon

**Comment by zhan-xu** [comment]
Thanks for this work! I am also putting this in README.

**Comment by L-Medici** [comment]
Oh my god thank you! We really appreciate your consideration of our work :D godspeed kind sir :)
