### ISSUE TITLE
Is it possible to have an example with a full pipeline for the preprocessing step?

### ISSUE THREAD

**Issue by dhorka** [zhan-xu/RigNet#54]
Hi,

I would like to ask if it could be possible to have a full example step by step of how an fbx file is converted to the data used to train the network with all the transformation needed for each of the subnetworks. 

Thanks!

**Comment by zhan-xu** [comment]
Hi. The current provided pipeline is, given a OBJ mesh, RigNet tries to predict its rig. The different between FBX and OBJ is, FBX can has rig already. I assume a more general using case is people trying to rig a OBJ mesh. 
If you have problem with converting FBX into OBJ, you can use for example Maya to load it and export it as an OBJ model maybe?
