### ISSUE TITLE
Metrics code

### ISSUE THREAD

**Issue by dhorka** [zhan-xu/RigNet#58]
Is it possible that you upload the code used for obtain the metrics reported in the paper? I am interested on the euclidean distance between deformed points.

**Comment by zhan-xu** [comment]
Do you mean the "avg dist" and "max dist" in skinning evaluation? This is done in Maya, where you can set small random rotations to a subset of randomly picked joints. The code for this would be hard to release. We add them simply for the comparison with NeuroSkinning paper.

**Comment by dhorka** [comment]
Could it be possible to have the code for the rest of the metrics? Precision, recall l1 distance and so on?

About the comparison with NeuroSkinning, I saw that there is no code for this paper.  have you implemented by yourselves the code? Is it possible to have it? I would like to know how did you implement the superskeleton approach using this dataset.

**Comment by zhan-xu** [comment]
OK, please tell me your email. I will send you some evaluation scripts.
For neuroskinning, I implemented their architecture. We cannot do super skeleton, since our skeletons are not aligned by names. For comparison, we compare between different architecture and, they sorted bones in terms of Euclidean distance.

**Comment by dhorka** [comment]
Here it is my [e-mail](mosehmf@gmail.com). But I think you should uploaded in the repo, I think it could be interesting to have it for the rest of the people. On the other hand, is it possible that you also share the neuroskinning architecture implementation?
