### ISSUE TITLE
Doubt in skinning weights generation step with a trained model

### ISSUE THREAD

**Issue by dhorka** [zhan-xu/RigNet#59]
Hi,
 I have a doubt related to the post-process done using the predicted values of the skinning weights. In the file run_skinning I found this line: https://github.com/zhan-xu/RigNet/blob/c5f5c985ca48700ac416b2f7f76a1fb3dde97554/run_skinning.py#L207

My doubt is why do you do that? I mean if I properly understand this line you are putting to zero all the values that  accomplish this condition max_value/2. Is there any technical justification for it?

A related doubt is that I found that this line is different in the quick start script https://github.com/zhan-xu/RigNet/blob/c5f5c985ca48700ac416b2f7f76a1fb3dde97554/quick_start.py#L338
Is there any reason that instead of using 0.5 here you are using 0.35?

**Comment by zhan-xu** [comment]
Hi @dhorka , there are parameters I tuned to get better results. They don't have particular technical justification. You can see them as a post filtering to the predicted weights, where we discard small numbers. 

The reason I use different threshold is also for the performance. The above one (0.5) achieves better numerical performance in the whole testing set. The below one (0.35) seems get better results for the visual results on the provided examples.
