### ISSUE TITLE
BBW and NeuroSkinning comparison

### ISSUE THREAD

**Issue by yorard123** [zhan-xu/RigNet#62]
Hi,

I would like to ask how did you make the comparison with neuroskinning. I saw that there is no code for this paper. Have you implemented it by yourself? Is it possible that you release the code of neuroskinning? I have been trying to implement it myself, but I think I am doing something wrong because I am getting completely different results.  I have the same issue with BBW. Is it possible to have your implementation of both methods?

Thanks!!

**Comment by DoubleCake** [comment]
Hi！Although it has been  more than 2 years.
The code of neuroskinning is still not released. We want to compare the results of this method on our own game dataset, do you still have your work ? Would you like  send us a copy? 
Looking forward to your reply！
