### ISSUE TITLE
Commercial use of the data?

### ISSUE THREAD

**Issue by XiaohangZhan** [zhan-xu/RigNet#64]
Hello, I'm wondering if the rignet data can be used for commercial purpose? Thank you!

**Comment by zhan-xu** [comment]
Unfortunately I don't think so... you will have to ask UMass tech transfer office and  them. see below.

Please contact the University of Massachusetts Amherst Technology Transfer Office at tto@umass.edu, and copy to kalo@cs.umass.edu and zhanxu@cs.umass.edu.
