### ISSUE TITLE
issues with quantitative evaluation

### ISSUE THREAD

**Issue by zzzark** [zhan-xu/RigNet#65]
i would like to perform quantitative evaluation (proposed in the paper), yet it seems that no related code included in the project ... 
( probably they are in somewhere but i promise i have searched many times )

**Comment by gjgjgjfff** [comment]
> Hi, I put the evaluation scripts [here](https://umass-my.sharepoint.com/:u:/g/personal/zhanxu_umass_edu/EWXdcIb_38xKoqyujQIQjzYBVsVY2c0p9rz2EtHUsif-pQ?e=04sref)
> 
> These are not very well organized. Please use as your reference.

Hi, the calculation code of dist metrics is not found in eval_skinning.py, can you provide relevant code?

**Comment by zjp-shadow** [comment]
Could you provide the metrics code again for evaluation? The link has expired. I cannot reproduce the results of the article precisely. Thanks a lot! @zhan-xu

**Comment by zhan-xu** [comment]
New [link](https://drive.google.com/file/d/1WrYEdcDQpj0b1pH1kD1QRXveojD6w_Vx/view?usp=drive_link) for the evaluation scripts. Please use them as reference.
