### ISSUE TITLE
Data licensing

### ISSUE THREAD

**Issue by heathermeeker** [zhan-xu/RigNet#80]
I understand that the RigNet data set https://github.com/zhan-xu/RigNet/ is offered under the GPL, which is a software license, not a data license, and leaves the requirements for using the data set unclear. I sent an email to UMass, as suggested, to inquire about alternative licensing terms that will specifically allow ML training, but no one responded.  Who can answer this question?

**Comment by zhan-xu** [comment]
could you send me an email about this zhanxu@cs.umass.edu
