### ISSUE TITLE
the link of Data is broken

### ISSUE THREAD

**Issue by ForrestPi** [zhan-xu/RigNet#94]
Hi, the link of Data is broken ,
https://umass-my.sharepoint.com/:u:/g/personal/zhanxu_umass_edu/EVgpX4uZEVNLu8OjX9JRaFYBzOjfm4znndui29evdEfs-g
https://umass-my.sharepoint.com/:u:/g/personal/zhanxu_umass_edu/EaUH-2lI6-xOrJ0N9fDbZOABREt4ryEtQ64wmELF5SReTg

could you update it?

**Comment by zhan-xu** [comment]
Hi, I have updated the links! Sorry for the late response.
