### ISSUE TITLE
Why data need to be consistently oriented?

### ISSUE THREAD

**Issue by Xin-97** [zhan-xu/RigNet#95]
Hi @zhan-xu , thanks for your wonderful work. 

I noticed in your papers that you mention, "Our only assumption is that the input training and test shapes have a consistent upright and front-facing orientation." Could you please explain the reason? Thanks!

**Comment by zhan-xu** [comment]
This is just to simplify the task, and reduce the difficulty for the networks to learn, given the scale of the dataset is only 3K.
